// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A prompt organization AI agent.
 *
 * - organizePrompt - A function that handles the prompt organization process.
 * - OrganizePromptInput - The input type for the organizePrompt function.
 * - OrganizePromptOutput - The return type for the organizePrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OrganizePromptInputSchema = z.object({
  promptText: z.string().describe('The prompt text to organize.'),
});

export type OrganizePromptInput = z.infer<typeof OrganizePromptInputSchema>;

const OrganizePromptOutputSchema = z.object({
  category: z.string().describe('The category of the prompt.'),
  tags: z.array(z.string()).describe('The tags for the prompt.'),
});

export type OrganizePromptOutput = z.infer<typeof OrganizePromptOutputSchema>;

export async function organizePrompt(input: OrganizePromptInput): Promise<OrganizePromptOutput> {
  return organizePromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'organizePromptPrompt',
  input: {schema: OrganizePromptInputSchema},
  output: {schema: OrganizePromptOutputSchema},
  prompt: `You are an AI assistant that helps organize prompts by categorizing them and adding relevant tags.

  Analyze the following prompt and determine its category and relevant tags.

  Prompt: {{{promptText}}}

  Return the category and tags in JSON format.
  `,
});

const organizePromptFlow = ai.defineFlow(
  {
    name: 'organizePromptFlow',
    inputSchema: OrganizePromptInputSchema,
    outputSchema: OrganizePromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
